# SITE SETUP
# Guide: https://docs.hugoblox.com/tutorial/
# Documentation: https://docs.hugoblox.com/
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

# Appearance
appearance:
  mode: system
  color: blue

# SEO
marketing:
  seo:
    site_type: Organization
    local_business_type: ''
    org_name: 'Turf Västerbotten'
    description: 'Föreningen för turfare i Västerbotten.'
    twitter: ''
  analytics:
    google_analytics: ''
    baidu_tongji: ''
    plausible: ''
    fathom: ''
    pirsch: ''
  verification:
    google: ''
    baidu: ''

# Site header
header:
  navbar:
    enable: true
    show_search: true
    show_theme_chooser: true

# Site footer
footer:
  copyright:
    notice: '© {year} Turf Västerbotten. This work is licensed under {license}'
    license:
      enable: true
      allow_derivatives: false
      share_alike: true
      allow_commercial: false

# Localization
locale:
  date_format: '02 January 2006'
  time_format: '15:04'
  address_format: fi

# Site features
features:
  math:
    enable: false
  privacy_pack:
    enable: false
  repository:
    url: ''
    content_dir: starters/blog/content
    branch: main
